### ISSUE TITLE
Lack of information in README.md

### ISSUE THREAD

**Issue by VanshKhera** [VanshKhera/Project-Zen#2]
@nob123456789 to make the README.md more maximized with:

- a clear description of the project
- upcoming features
- current features

I'll be working with the backend

**Comment by nob123456789** [comment]
What exactly on the backend, are you already starting on the main css library??

**Comment by nob123456789** [comment]
I'll be continuing with the home page design for the time being
Please take incharge of js though bcs im not familiar with it
